# Generated by Django 3.2.2 on 2021-05-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210514_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='genres',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='main.Genre', verbose_name='genres'),
        ),
    ]
