# Generated by Django 3.2.2 on 2021-05-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tagline',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=models.URLField(default=None, null=True, verbose_name='Video URL'),
        ),
    ]
